let setLang = () => {
	let lang = localStorage.lang;
	let changeNodeList = Array.prototype.slice.call(document.querySelectorAll('[data-text]'));
	changeNodeList.map( v => {
	  v.textContent = resource[lang][v.dataset.text]
	})
	let changeHolderList = Array.prototype.slice.call(document.querySelectorAll('[data-holder]'));
	changeHolderList.map( v => {
	  v.placeholder = resource[lang][v.dataset.holder]
	})
};

let resource = {
    "ko" : {
      WORKING_HOUR: "에너지 절약을 위하여 평일 09:00 부터 19:00 까지만 운영합니다.",
      POWERED_BY_EFORMSIGNAPI: "Powered by eformsign API",
      INVALID_MEMBER: "유효하지 않은 로그인 정보입니다.",
      SYSNAME: "전자문서 시스템",
      LOGINID: "로그인 ID",
      PASSWORD: "패스워드",
      LOGIN: "로그인",
      COMPANY: "Green Tech",
      CREATE_DOCUMENT: "문서 작성",
	  CREATE_DOCUMENT_SINGLEDATA: "문서 작성(데이터 표시)",
      DOCUMENT_BOX: "문서함",
      TEMPLATE_MNGT: "템플릿 관리",
      MEMBER_MNGT: "멤버 관리",
      GROUP_MNGT: "그룹 관리",
      LOGOUT: "로그아웃",
      TEMPLATES: "템플릿 리스트",
      CATEGORY: "카테고리",
      FIND: "검색",
      FROM_MY_FILE: "내파일로 작성",
      FROM_TEMPLATE: "템플릿으로 작성",
      BULK_DOCUMENTS: "데이터연동 / 일괄전송",
      VIEW_COMPLETE: "완료문서 보기",
      SELECT_TEMPLATE: "템플릿을 선택하세요",
      RECIPIENT_LIST: "수신자 목록",
      RECIPIENT_TYPE: "수신자 타입",
      RECIPIENT_TYPE_EXTERNAL: "외부자",
      RECIPIENT_TYPE_PARTICIPANT: "참여자",
      RECIPIENT_TYPE_REVIEWER: "검토자",
      RECIPIENT_TYPE_VIEWER: "열람자",
      RECIPIENT_NAME: "수신자(필수)",
      RECIPIENT_EMAIL: "이메일(필수)",
      RECIPIENT_MOBILE: "핸드폰",
      RECIPIENT_DATA: "데이터",
      SEND: "전송",
      PROCESS: "작성",
      SELECT: "수신자 선택",
      SELECTED: "선택 완료",
      SEND_EMBED: "선택 전송(Embed)",
      SEND_SINGLE: "선택 전송",
      SEND_BULK: "일괄 전송",
      CLEAR_SELECTIONS: "선택 해제",
      IN_PROGRESS: "진행중 문서함",
      ACTION_REQUIRED: "처리할 문서함",
      COMPLETED: "완료 문서함",
      DOCUMENT_MNGT: "문서 관리",
      SELECTED_DOCUMENT: "선택한 문서",
      VIEW: "보기",
      INFO: "상세정보",
      DOWNLOAD: "다운로드",
      ATTACHMENTS: "첨부파일",
      CANCEL: "취소",
      DELETE: "삭제",
      EDIT: "수정",
      NEW: "생성",
      TEMPLATE_NAME: "템플릿 명",
      CREATE_TEMPLATE: "시작",
      MEMBER_LIST: "멤버 리스트",
      GROUP_LIST: "그룹 리스트",
      ADD: "추가",
      DEMO_CATEGORY: "krdemo",
      SVC_TOKEN_RECEIVED: "토큰을 받았습니다.",
      SVC_TOKEN_REFRESHED: "토큰을 갱신했습니다.",
      SVC_SELECT_RECIPIENT: "수신자를 선택하세요.",
      SVC_TEMPLATE_LIST_INITIALIZING: "서버 연결중...",
      SVC_TEMPLATE_LIST_RECEIVING: "템플릿 리스트 수신중...",
      SVC_TEMPLATE_LIST_RECEIVED: "템플릿 리스트를 받았습니다.",
      SVC_TEMPLATE_LIST_CATEGORY: "카테고리",
      SVC_TEMPLATE_LIST_NAME: "템플릿명",
      SVC_TEMPLATE_LIST_CREATOR: "작성자",
      SVC_TEMPLATE_LIST_OWNER: "소유자",
      SVC_TEMPLATE_LIST_UPDATOR: "수정자",
      SVC_TEMPLATE_LIST_UPDATED: "수정일",
      SVC_TEMPLATE_LIST_PUBLISHED: "배포일",
      SVC_TEMPLATE_LIST_VERSION: "버전",
      SVC_TEMPLATE_LIST_ENABLED: "사용가능",
      SVC_TEMPLATE_LIST_DESC: "설명",
      SVC_TEMPLATE_LIST_SELECT: "템플릿을 선택하세요.",
      SVC_DOC_LIST_TEMPLATE: "템플릿",
      SVC_DOC_LIST_DOCUMENT: "문서",
      SVC_DOC_LIST_STEP: "단계",
      SVC_DOC_LIST_CREATOR: "작성자",
      SVC_DOC_LIST_CREATED: "작성일",
      SVC_DOC_LIST_LAST_UPDATER: "최종 처리자",
      SVC_DOC_LIST_LAST_UPDATED: "최종 처리일",
      SVC_DOC_LIST_RECEIVING: "문서 리스트 수신중...",
      SVC_DOC_LIST_RECEIVED: "문서 리스트를 받았습니다.",
      SVC_DOC_LIST_DELETED: "문서가 삭제되었습니다.",
      SVC_DOC_LIST_SELECT: "문서를 선택하세요.",
      SVC_MEMBER_ADMIN: "멤버 관리",
      SVC_MEMBER_LIST_ID: "ID",
      SVC_MEMBER_LIST_NAME: "멤버",
      SVC_MEMBER_LIST_CREATED: "가입일",
      SVC_MEMBER_LIST_ENABLED: "활성화",
      SVC_MEMBER_LIST_WITHDRAWN: "탈퇴",
      SVC_MEMBER_LIST_COUNTRYCODE: "국가코드",
      SVC_MEMBER_LIST_MOBILE: "휴대폰",
      SVC_MEMBER_LIST_ROLE: "권한",
      SVC_MEMBER_LIST_GROUP: "그룹",
      SVC_MEMBER_LIST_DELETED: "삭제",
      SVC_MEMBER_LIST_RECEIVED: "멤버 리스트를 받았습니다.",
      SVC_GROUP_ADMIN: "그룹 관리",
      SVC_GROUP_LIST_ID: "ID",
      SVC_GROUP_LIST_NAME: "그룹명",
      SVC_GROUP_LIST_CREATED: "생성일",
      SVC_GROUP_LIST_MEMBER: "멤버",
      SVC_GROUP_LIST_DESC: "설명",
      SVC_GROUP_LIST_RECEIVED: "그룹 리스트를 받았습니다.",
      SVC_RECIPIENT_LIST_NAME: "수신자",
      SVC_RECIPIENT_LIST_EMAIL: "이메일",
      SVC_RECIPIENT_LIST_MOBILE: "핸드폰",
      SVC_RECIPIENT_LIST_DATA: "데이터",
      SVC_RECIPIENT_LIST_SELECTED: "선택한 수신자: ",
      SVC_RECIPIENT_LIST_RECEIVED: "수신자 리스트를 받았습니다.",
      SVC_RECIPIENT_LIST_SENDING_REQUEST: "문서 전송 요청중입니다...",
      SVC_RECIPIENT_LIST_SENT_REQUEST: "전송이 완료되었습니다.",
      HTML_SELECT_DATASOURCE: "데이터소스를 선택하세요.",
      HTML_NO_DATASOURCE: "데이터 없음",
      HTML_DOCUMENT_SENT: "문서가 전송되었습니다."
    },
    "en" : {
      WORKING_HOUR: "To save energy, we open from KST 09:00 to 19:00 on weekdays.",
      POWERED_BY_EFORMSIGNAPI: "Powered by eformsign API",
      INVALID_MEMBER: "Invalid login credentials.",
      SYSNAME: "e-Document System",
      LOGINID: "Login ID",
      PASSWORD: "Password",
      LOGIN: "Login",
      COMPANY: "Green Tech",
      CREATE_DOCUMENT: "Create Document",
	  CREATE_DOCUMENT_SINGLEDATA: "Create Document(View Data)",
      SEND_EMBED: "Send Single(Embed)",
      SEND_SINGLE: "Send Single",
      SEND_BULK: "Send Bulk",
      DOCUMENT_BOX: "Document Box",
      TEMPLATE_MNGT: "Templates",
      MEMBER_MNGT: "Members",
      GROUP_MNGT: "Groups",
      LOGOUT: "Logout",
      TEMPLATES: "Template list",
      CATEGORY: "Category",
      FIND: "Find",
      FROM_MY_FILE: "From my file",
      FROM_TEMPLATE: "From template",
      BULK_DOCUMENTS: "Prefill / Bulk",
      VIEW_COMPLETE: "View response",
      SELECT_TEMPLATE: "Select your template.",
      RECIPIENT_LIST: "Recipient List",
      RECIPIENT_TYPE: "Recipient type",
      RECIPIENT_TYPE_EXTERNAL: "External User",
      RECIPIENT_TYPE_PARTICIPANT: "Participant",
      RECIPIENT_TYPE_REVIEWER: "Reviewer",
      RECIPIENT_TYPE_VIEWER: "Viewer",
      RECIPIENT_NAME: "Recipient(required)",
      RECIPIENT_EMAIL: "Email(required)",
      RECIPIENT_MOBILE: "Mobile(optional)",
      RECIPIENT_DATA: "Data(optional)",
      SEND: "Send",
      PROCESS: "Process",
      SELECT: "Choose recipients",
      SELECTED: "Select",
      CLEAR_SELECTIONS: "Clear selctions",
      IN_PROGRESS: "In progress",
      ACTION_REQUIRED: "Action required",
      COMPLETED: "Completed",
      DOCUMENT_MNGT: "Document Admin",
      SELECTED_DOCUMENT: "Select a document and",
      VIEW: "View",
      INFO: "Details",
      DOWNLOAD: "Download",
      ATTACHMENTS: "Attachements",
      DELETE: "Delete",
      CANCEL: "Cancel",
      EDIT: "Edit",
      NEW: "New",
      TEMPLATE_NAME: "Template name",
      CREATE_TEMPLATE: "Start",
      MEMBER_LIST: "Member list",
      GROUP_LIST: "Group list",
      ADD: "Add",
      DEMO_CATEGORY: "krdemo",
      SVC_TOKEN_RECEIVED: "Token received.",
      SVC_TOKEN_REFRESHED: "Token refreshed.",
      SVC_SELECT_RECIPIENT: "Select recipient(s).",
      SVC_TEMPLATE_LIST_INITIALIZING: "Connecting to the server...",
      SVC_TEMPLATE_LIST_RECEIVING: "Template list receiving...",
      SVC_TEMPLATE_LIST_RECEIVED: "Template list received.",
      SVC_TEMPLATE_LIST_CATEGORY: "Category",
      SVC_TEMPLATE_LIST_NAME: "Name",
      SVC_TEMPLATE_LIST_CREATOR: "Creator",
      SVC_TEMPLATE_LIST_OWNER: "Owner",
      SVC_TEMPLATE_LIST_UPDATOR: "Updator",
      SVC_TEMPLATE_LIST_UPDATED: "Updated",
      SVC_TEMPLATE_LIST_VERSION: "Version",
      SVC_TEMPLATE_LIST_ENABLED: "Enabled",
      SVC_TEMPLATE_LIST_DESC: "Description",
      SVC_TEMPLATE_LIST_SELECT: "Select your template.",
      SVC_DOC_LIST_TEMPLATE: "Template", 
      SVC_DOC_LIST_DOCUMENT: "Document",
      SVC_DOC_LIST_STEP: "Step",
      SVC_DOC_LIST_CREATOR: "Sender",
      SVC_DOC_LIST_CREATED: "Sent",
      SVC_DOC_LIST_LAST_UPDATER: "Submitter",
      SVC_DOC_LIST_LAST_UPDATED: "Submitted",
      SVC_DOC_LIST_RECEIVING: "Document list receiving...",
      SVC_DOC_LIST_RECEIVED: "Document list received.",
      SVC_DOC_LIST_DELETED: "Document deleted.",
      SVC_DOC_LIST_SELECT: "Select a document.",
      SVC_MEMBER_ADMIN: "Members",
      SVC_MEMBER_LIST_ID: "ID",
      SVC_MEMBER_LIST_NAME: "Name",
      SVC_MEMBER_LIST_CREATED: "Subscribed",
      SVC_MEMBER_LIST_ENABLED: "Enabled",
      SVC_MEMBER_LIST_WITHDRAWN: "Withdrawal",
      SVC_MEMBER_LIST_COUNTRYCODE: "Country code",
      SVC_MEMBER_LIST_MOBILE: "Mobile",
      SVC_MEMBER_LIST_ROLE: "Role",
      SVC_MEMBER_LIST_GROUP: "Group",
      SVC_MEMBER_LIST_DELETED: "Deleted",
      SVC_MEMBER_LIST_RECEIVED: "Member list received.",
      SVC_GROUP_ADMIN: "Group Admin",
      SVC_GROUP_LIST_ID: "ID",
      SVC_GROUP_LIST_NAME: "Name",
      SVC_GROUP_LIST_CREATED: "Created",
      SVC_GROUP_LIST_MEMBER: "Member",
      SVC_GROUP_LIST_DESC: "Description",
      SVC_GROUP_LIST_RECEIVED: "Group list received.",
      SVC_RECIPIENT_LIST_NAME: "Recipient",
      SVC_RECIPIENT_LIST_EMAIL: "Email",
      SVC_RECIPIENT_LIST_MOBILE: "Mobile",
      SVC_RECIPIENT_LIST_DATA: "Data",
      SVC_RECIPIENT_LIST_SELECTED: "Selected recipients: ",
      SVC_RECIPIENT_LIST_RECEIVED: "Recipient list received.",
      SVC_RECIPIENT_LIST_SENDING_REQUEST: "Sending document request...",
      SVC_RECIPIENT_LIST_SENT_REQUEST: "Document has been sent.",
      HTML_SELECT_DATASOURCE: "Load data from:",
      HTML_NO_DATASOURCE: "No data",
      HTML_DOCUMENT_SENT: "Docuement has been sent successfuly."
    },
    "ja" : {
      WORKING_HOUR: "省エネのため、平日はKST09:00~19:00まで営業しています。",
      POWERED_BY_EFORMSIGNAPI: "eformsign APIによって提供",
      INVALID_MEMBER: "無効なログイン情報です",
      SYSNAME: "電子文書システム",
      LOGINID: "ログイン ID",
      PASSWORD: "パスワード",
      LOGIN: "ログイン",
      COMPANY: "Green Tech",
      CREATE_DOCUMENT: "文書作成",
	  CREATE_DOCUMENT_SINGLEDATA: "文書作成(データ表示)",
      BULK_DOCUMENTS: "データ連携 / 一括送信",
      DOCUMENT_BOX: "文書箱",
      TEMPLATE_MNGT: "テンプレート管理",
      MEMBER_MNGT: "メンバー管理",
      GROUP_MNGT: "グループ管理",
      LOGOUT: "ログアウト",
      TEMPLATES: "テンプレートリスト",
      CATEGORY: "カテゴリー",
      FIND: "検索",
      FROM_MY_FILE: "マイファイルで作成",
      FROM_TEMPLATE: "テンプレートで作成",
      VIEW_COMPLETE: "完了文書照会",
      SELECT_TEMPLATE: "テンプレートを選択してください。",
      RECIPIENT_TYPE: "受信者タイプ",
      RECIPIENT_TYPE_EXTERNAL: "スタート",
      RECIPIENT_TYPE_PARTICIPANT: "参加者",
      RECIPIENT_TYPE_REVIEWER: "検討者",
      RECIPIENT_TYPE_VIEWER: "閲覧者",
      RECIPIENT_NAME: "受信者(必須)",
      RECIPIENT_EMAIL: "メール(必須)",
      RECIPIENT_MOBILE: "けいたい(選択)",
      RECIPIENT_DATA: "データ(選択)",
      SEND: "送信",
      PROCESS: "作成",
      SELECT: "受信者選択",
      SELECTED: "選択完了",
      SEND_EMBED: "選択送信(Embed)",
      SEND_SINGLE: "選択送信",
      SEND_BULK: "一括送信",
      CLEAR_SELECTIONS: "選択解除",
      IN_PROGRESS: "進行中文書箱",
      ACTION_REQUIRED: "処理する文書箱",
      COMPLETED: "完了文書箱",
      DOCUMENT_MNGT: "文書管理",
      SELECTED_DOCUMENT: "選択した文書を",
      VIEW: "ビュー",
      INFO: "詳細",
      DOWNLOAD: "ダウンロード",
      ATTACHMENTS: "添付ファイル",
      DELETE: "削除",
      EDIT: "修正",
      NEW: "ニューテ",
      TEMPLATE_NAME: "テンプレート名",
      CREATE_TEMPLATE: "スタート",
      MEMBER_LIST: "メンバーリスト",
      GROUP_LIST: "グループリスト",
      ADD: "追加",
      DEMO_CATEGORY: "jpdemo",
      DOCUMENT_SENT: "文書が送信されました。",
      SVC_TOKEN_RECEIVED: "トークンを受け取りました。",
      SVC_TOKEN_REFRESHED: "トークンが更新されました。",
      SVC_SELECT_RECIPIENT: "受信者を選択してください。",
      SVC_TEMPLATE_LIST_INITIALIZING: "サーバーに接続中...",
      SVC_TEMPLATE_LIST_RECEIVING: "テンプレートリスト受信中...",
      SVC_TEMPLATE_LIST_RECEIVED: "テンプレートリストを受け取りました。",
      SVC_TEMPLATE_LIST_CATEGORY: "カテゴリー",
      SVC_TEMPLATE_LIST_NAME: "テンプレート",
      SVC_TEMPLATE_LIST_CREATOR: "作り手",
      SVC_TEMPLATE_LIST_OWNER: "所有者",
      SVC_TEMPLATE_LIST_UPDATOR: "修正者",
      SVC_TEMPLATE_LIST_UPDATED: "修正日",
      SVC_TEMPLATE_LIST_VERSION: "バージョン",
      SVC_TEMPLATE_LIST_ENABLED: "使用可能",
      SVC_TEMPLATE_LIST_DESC: "内容",
      SVC_TEMPLATE_LIST_SELECT: "テンプレートを選択してください。",
      SVC_DOC_LIST_TEMPLATE: "テンプレート名", 
      SVC_DOC_LIST_DOCUMENT: "文書名",
      SVC_DOC_LIST_STEP: "ステップ",
      SVC_DOC_LIST_CREATOR: "作成者",
      SVC_DOC_LIST_CREATED: "作成日",
      SVC_DOC_LIST_LAST_UPDATER: "処理者",
      SVC_DOC_LIST_LAST_UPDATED: "処理日",
      SVC_DOC_LIST_RECEIVING: "文書リスト受信中.....",
      SVC_DOC_LIST_RECEIVED: "文書リストを受け取りました。",
      SVC_DOC_LIST_DELETED: "削除されました。.",
      SVC_DOC_LIST_SELECT: "文書を選択してください。",
      SVC_MEMBER_ADMIN: "メンバー管理",
      SVC_MEMBER_LIST_ID: "ID",
      SVC_MEMBER_LIST_NAME: "メンバー名",
      SVC_MEMBER_LIST_CREATED: "加入日",
      SVC_MEMBER_LIST_ENABLED: "活性化",
      SVC_MEMBER_LIST_WITHDRAWN: "脱退",
      SVC_MEMBER_LIST_COUNTRYCODE: "国コード",
      SVC_MEMBER_LIST_MOBILE: "携帯番号",
      SVC_MEMBER_LIST_ROLE: "権限",
      SVC_MEMBER_LIST_GROUP: "所属グループ名",
      SVC_MEMBER_LIST_DELETED: "削除",
      SVC_MEMBER_LIST_RECEIVED: "メンバーリストを受け取りました。",
      SVC_GROUP_ADMIN: "グループ管理",
      SVC_GROUP_LIST_ID: "ID",
      SVC_GROUP_LIST_NAME: "グループ名",
      SVC_GROUP_LIST_CREATED: "生成日",
      SVC_GROUP_LIST_MEMBER: "所属メンバー",
      SVC_GROUP_LIST_DESC: "備考",
      SVC_GROUP_LIST_RECEIVED: "グループリストを受け取りました。",
      SVC_RECIPIENT_LIST_NAME: "受信者",
      SVC_RECIPIENT_LIST_EMAIL: "メールアドレス",
      SVC_RECIPIENT_LIST_MOBILE: "携帯",
      SVC_RECIPIENT_LIST_DATA: "データ",
      SVC_RECIPIENT_LIST_SELECTED: "選択された受信者: ",
      SVC_RECIPIENT_LIST_RECEIVED: "受信者リストを受け取りました。",
      SVC_RECIPIENT_LIST_SENDING_REQUEST: "文書送信要請中です···",
      SVC_RECIPIENT_LIST_SENT_REQUEST: "文書が送信されました。",
      HTML_SELECT_DATASOURCE: "データファイル選択",
      HTML_NO_DATASOURCE: "データなし",
      HTML_DOCUMENT_SENT: "文書が送信されました。"
    }
  };