curl
-X GET
-H "Content-Type: application/json"
-H "Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJlZm9ybXNpZ24uaWFtIiwiY29udGV4dCI6eyJjbGllbnRJZCI6IjY4MDk0ZWVhMjVhZjRhNjI5ZTI4ZGU5Y2ZlYzRlYmZjIiwiY2xpZW50S2V5IjoiZTNiM2IzZTUtMGEzMS00NTE1LWE5NzEtN2M4Y2FlNDI4NzZmIiwibWFuYWdlbWVudElkIjoiMzRhYWI4MDBjMmEwNDQwNThmZDRlZjc5OGFlY2RlY2EiLCJzY29wZXMiOiJzbWFydF9lZm9ybV9zY29wZSIsInR5cGUiOiJ1c2VyIiwidXNlck5hbWUiOiJram01OTk1QGdtYWlsLmNvbSIsInVzZXJJZCI6IjVjZTFiYzIxMjY3NTRmYWFhMDdkMTYyODUzMmQ1MzdjIiwicmVmcmVzaFRva2VuIjoiMjc0N2FjMDYtZjU1MC00ZDc0LTg2YjMtNzVhY2EzYWEwMzY4In0sImNsYWltIjp7Im1lbWJlcl9pZCI6ImtqbTU5OTVAZ21haWwuY29tIiwiY29tcGFueV9pZCI6ImE5YzJjMGZmZjMwMDRhN2U5NDRmNWM0YjhmN2Q4M2Q0IiwiYWNjZXNzX2tleSI6ImM1YzI5MWM1LTIzZTMtNDg3OC05NWFjLTMxZDhlNWUzNDczYSJ9LCJleHAiOjE2OTE4Mjg2OTYsImlhdCI6MTY5MTgyNTA5Nn0.BGV18_HaURZpBa3OSnTlrNVh53c0dYggEB_gJfW5AXAFt9v7z05W3CNJo5LnQyjf9Op5ueTHrWew0NGBMvC_QnSlJTyCISj__eaezSblJK-Mkka5NGFq-MX7HZQW7yYif_napmHu3x1j2raAf2Rs1TD5gjK4ZWpO-SJEHJnGX6c"
'http://anycar.ap-northeast-2.elasticbeanstalk.com/api/get/outside_token?name=Jorge&email=jorgedavid@forcs.com'